# SPDX-FileCopyrightText: 2025 Koen van Greevenbroek
#
# SPDX-License-Identifier: CC-BY-4.0

# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py
  fail_on_warning: false

# Build all formats (HTML, PDF, EPUB)
formats:
  - pdf
  - epub

# Python environment
build:
  os: ubuntu-24.04
  tools:
    python: "3.12"

# Install dependencies
python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - dev
