# SPDX-FileCopyrightText: 2025 Koen van Greevenbroek
#
# SPDX-License-Identifier: CC-BY-4.0

version = 1
SPDX-PackageName = "food-opt"
SPDX-PackageSupplier = "Koen van Greevenbroek"
SPDX-PackageDownloadLocation = "https://github.com/koen-vg/food-opt"

[[annotations]]
path = "data/**.csv"
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 Koen van Greevenbroek"
SPDX-License-Identifier = "PDDL-1.0"