# SPDX-FileCopyrightText: 2025 Koen van Greevenbroek
#
# SPDX-License-Identifier: CC-BY-4.0

name: "toy"

primary:
  land:
    limit: 1e9 # ha
  water:
    limit: 1e9 # m^3
  fertilizer:
    limit: 1e9 # kg

crops:
- wheat
- dryland rice
- wetland rice
- maize
- soybean
- white potato
- tomato
- barley
- oat
- sunflower
- carrot
- onion
- cabbage
- banana

population: 7000000000 # Approx world population

macronutrients:
  carb:
    min_per_person_per_day: 300  # g/person/day (45-65% of calories, ~2000 cal/day)
  protein:
    min_per_person_per_day: 50   # g/person/day (10-35% of calories)
  fat:
    min_per_person_per_day: 65   # g/person/day (20-35% of calories)

food_groups:
  whole grain:
    min_per_person_per_day: 170  # g/person/day (WHO recommendations)
  grain:
    min_per_person_per_day: 150  # g/person/day (refined grains)
  fruit:
    min_per_person_per_day: 200  # g/person/day (WHO: 400g fruit+veg, split evenly)
  vegetable:
    min_per_person_per_day: 200  # g/person/day (WHO: 400g fruit+veg, split evenly)
  starchy vegetable:
    min_per_person_per_day: 100  # g/person/day (potatoes, etc.)
  oil:
    min_per_person_per_day: 25   # g/person/day (essential fats)

aggregation:
  regions: "states"  # Options: "countries", "states"
  resource_class_quantiles: [0.25, 0.5, 0.75]

countries:
# - ABW  # No level-1 GADM data
- AFG
- AGO
- AIA
- ALA
- ALB
- AND
- ARE
- ARG
- ARM
- ASM
# - ATA  # No level-1 GADM data
- ATF
- ATG
- AUS
- AUT
- AZE
- BDI
- BEL
- BEN
- BES
- BFA
- BGD
- BGR
- BHR
- BHS
- BIH
- BLM
- BLR
- BLZ
- BMU
- BOL
- BRA
- BRB
- BRN
- BTN
# - BVT  # No level-1 GADM data
- BWA
- CAF
- CAN
# - CCK  # No level-1 GADM data
- CHE
- CHL
- CHN
- CIV
- CMR
- COD
- COG
- COK
- COL
- COM
- CPV
- CRI
- CUB
# - CUW  # No level-1 GADM data
# - CXR  # No level-1 GADM data
- CYM
- CYP
- CZE
- DEU
- DJI
- DMA
- DNK
- DOM
- DZA
- ECU
- EGY
- ERI
- ESH
- ESP
- EST
- ETH
- FIN
- FJI
# - FLK  # No level-1 GADM data
- FRA
- FRO
- FSM
- GAB
- GBR
- GEO
- GGY
- GHA
# - GIB  # No level-1 GADM data
- GIN
- GLP
- GMB
- GNB
- GNQ
- GRC
- GRD
- GRL
- GTM
- GUF
- GUM
- GUY
# - HKG  # No level-1 GADM data
# - HMD  # No level-1 GADM data
- HND
- HRV
- HTI
- HUN
- IDN
- IMN
- IND
# - IOT  # No level-1 GADM data
- IRL
- IRN
- IRQ
- ISL
- ISR
- ITA
- JAM
- JEY
- JOR
- JPN
- KAZ
- KEN
- KGZ
- KHM
# - KIR  # No level-1 GADM data
- KNA
- KOR
- KWT
- LAO
- LBN
- LBR
- LBY
- LCA
- LIE
- LKA
- LSO
- LTU
- LUX
- LVA
# - MAC  # No level-1 GADM data
# - MAF  # No level-1 GADM data
- MAR
# - MCO  # No level-1 GADM data
- MDA
- MDG
# - MDV  # No level-1 GADM data
- MEX
- MHL
- MKD
- MLI
- MLT
- MMR
- MNE
- MNG
- MNP
- MOZ
- MRT
- MSR
- MTQ
- MUS
- MWI
- MYS
- MYT
- NAM
- NCL
- NER
# - NFK  # No level-1 GADM data
- NGA
- NIC
# - NIU  # No level-1 GADM data
- NLD
- NOR
- NPL
- NRU
- NZL
- OMN
- PAK
- PAN
# - PCN  # No level-1 GADM data
- PER
- PHL
- PLW
- PNG
- POL
- PRI
- PRK
- PRT
- PRY
- PSE
- PYF
- QAT
- REU
- ROU
- RUS
- RWA
- SAU
- SDN
- SEN
- SGP
# - SGS  # No level-1 GADM data
- SHN
- SJM
- SLB
- SLE
- SLV
- SMR
- SOM
- SPM
- SRB
- SSD
- STP
- SUR
- SVK
- SVN
- SWE
- SWZ
# - SXM  # No level-1 GADM data
- SYC
- SYR
- TCA
- TCD
- TGO
- THA
- TJK
- TKL
- TKM
- TLS
- TON
- TTO
- TUN
- TUR
- TUV
- TWN
- TZA
- UGA
- UKR
- UMI
- URY
- USA
- UZB
# - VAT  # No level-1 GADM data
- VCT
- VEN
- VGB
- VIR
- VNM
- VUT
- WLF
- WSM
- YEM
- ZAF
- ZMB
- ZWE

data:
  gaez:
    climate_model: "NorESM1-M"
    time_period: "2020s" # "2020s", "2050s", "2080s"; these are 30 year averages from climate ensembles centered on the given decade.
    rcp: "4p5" # "2p6", "4p5", "6p0", "8p5"
    input_management: "H" # "H" (High), "L" (Low)
    water_supply: "r" # "r" (rainfed), "i" (irrigated)
    co2_fertilization: "" # "" (with) or "0" (without)
    yield_var: "yc" # "Average attainable yield, current cropland" (GAEZ documentation, page 129)
    suitability_var: "sx1" # "Share of gridcell assessed as VS or S" (i.e. very suitable or suitable; GAEZ documentation, page 129)
    crops:
      alfalfa: alf
      banana: ban
      buckwheat: bck
      barley: brl
      biomass sorghum: bsg
      cabbage: cab
      carrot: car
      chickpea: chk
      citrus: cit
      cocoa: coc
      coffee: cof
      coconut: con
      cotton: cot
      cowpea: cow
      cassava: csv
      flax: flx
      foxtail millet: fml
      groundnut: grd
      gram: grm
      jatropha: jtr
      miscanthus: mis
      maize: mze
      silage maize: mzs
      napier grass: nap
      oat: oat
      oil palm: olp
      olive: olv
      onion: oni
      dry pea: pea
      phaseolus bean: phb
      pigeonpea: pig
      pearl millet: pml
      dryland rice: rcd
      reed canary grass: rcg
      wetland rice: rcw
      rapeseed: rsd
      rubber: rub
      rye: rye
      sunflower: sfl
      soybean: soy
      sweet potato: spo
      sorghum: srg
      sugarbeet: sub
      sugarcane: suc
      switchgrass: swg
      tea: tea
      tobacco: tob
      tomato: tom
      wheat: whe
      white potato: wpo
      yam: yam

solving:
  solver: gurobi
  solver_options:
    LogToConsole: 1
    OutputFlag: 1
