# SPDX-FileCopyrightText: 2025 Koen van Greevenbroek
#
# SPDX-License-Identifier: CC-BY-4.0

name: "toy"

planning_horizon: 2030

primary:
  land:
    limit: 1e9 # ha
    regional_limit: 0.7 # fraction of each region's potential cropland that is made available.
  water:
    limit: 1e9 # m^3
  fertilizer:
    limit: 1e9 # kg

emissions:
  ghg_price: 200 # USD/tCO2

crops:
- wheat
- dryland-rice
- wetland-rice
- maize
- soybean
- white-potato
- tomato
- barley
- oat
- sunflower
- carrot
- onion
- cabbage
- banana
- cassava
- sweet-potato
- yam
- sugarcane
- sugarbeet
- rapeseed
- groundnut
- rye
- dry-pea
- chickpea
- alfalfa
- biomass-sorghum
- silage-maize

macronutrients:
  carb:
    min_per_person_per_day: 300  # g/person/day (45-65% of calories, ~2000 cal/day)
  protein:
    min_per_person_per_day: 50   # g/person/day (10-35% of calories)
  fat:
    min_per_person_per_day: 65   # g/person/day (20-35% of calories)

animal_products:
  include:
  - cattle meat
  - pig meat
  - chicken meat
  - dairy
  - eggs

grazing:
  enabled: true

food_groups:
  whole grain:
    min_per_person_per_day: 170  # g/person/day (WHO recommendations)
  grain:
    min_per_person_per_day: 150  # g/person/day (refined grains)
  fruit:
    min_per_person_per_day: 200  # g/person/day (WHO: 400g fruit+veg, split evenly)
  vegetable:
    min_per_person_per_day: 200  # g/person/day (WHO: 400g fruit+veg, split evenly)
  starchy vegetable:
    min_per_person_per_day: 100  # g/person/day (potatoes, etc.)
  oil:
    min_per_person_per_day: 25   # g/person/day (essential fats)

trade:
  crop_hubs: 20
  crop_trade_marginal_cost_per_km: 1e-1
  non_tradable_crops:
  - alfalfa
  - biomass-sorghum
  - silage-maize

health:
  region_clusters: 30
  reference_year: 2018
  intake_grid_step: 10
  log_rr_points: 10
  # value_of_statistical_life: "regional" to use DIA regional values, or a
  # numeric constant in USD to override
  value_of_statistical_life: 10_000_000
  risk_factors:
  - fruits
  - vegetables
  - nuts_seeds
  - legumes
  - fish
  - red_meat
  - prc_meat
  - whole_grains

aggregation:
  regions:
    type: "cluster"
    target_count: 500
    allow_cross_border: false
    method: "kmeans"
  simplify_tolerance_km: 5
  simplify_min_area_km: 25
  resource_class_quantiles: [0.25, 0.5, 0.75]
  # Crop land-use limitation source used when aggregating yields by region/resource class.
  # - "suitability": limit area using GAEZ suitability rasters per water supply (irrigated/rainfed)
  # - "irrigated": limit area using the irrigated cropland share (for irrigated) and its complement (for rainfed)
  land_limit_dataset: "suitability"

countries:
# - ABW  # No level-1 GADM data
- AFG
- AGO
# - AIA  # No regions (microstate)
# - ALA  # No population
- ALB
# - AND  # excluded: microstate
- ARE
- ARG
- ARM
- ASM
# - ATA  # No level-1 GADM data
# - ATF  # No population
- ATG
- AUS
- AUT
- AZE
- BDI
- BEL
- BEN
# - BES  # excluded: small overseas territory
- BFA
- BGD
- BGR
# - BHR  # excluded: desert city-state
- BHS
- BIH
# - BLM  # No regions (microstate)
- BLR
- BLZ
# - BMU  # No regions (microstate)
- BOL
- BRA
- BRB
- BRN
- BTN
# - BVT  # No level-1 GADM data
- BWA
- CAF
- CAN
# - CCK  # No level-1 GADM data
- CHE
- CHL
- CHN
- CIV
- CMR
- COD
- COG
# - COK  # excluded: small island territory
- COL
- COM
- CPV
- CRI
- CUB
# - CUW  # No level-1 GADM data
# - CXR  # No level-1 GADM data
# - CYM  # excluded: small overseas territory
- CYP
- CZE
- DEU
- DJI
# - DMA  # excluded: small island state
- DNK
- DOM
- DZA
- ECU
- EGY
- ERI
# - ESH  # excluded: sparse desert territory
- ESP
- EST
- ETH
- FIN
- FJI
# - FLK  # No level-1 GADM data
- FRA
# - FRO  # excluded: small island territory
# - FSM  # excluded: small island state
- GAB
- GBR
- GEO
# - GGY  # Too small
- GHA
# - GIB  # No level-1 GADM data
- GIN
# - GLP  # excluded: overseas department
- GMB
- GNB
- GNQ
- GRC
- GRD
# - GRL  # excluded: ice-dominated
- GTM
- GUF
# - GUM  # excluded: small island territory
- GUY
# - HKG  # No level-1 GADM data
# - HMD  # No level-1 GADM data
- HND
- HRV
- HTI
- HUN
- IDN
# - IMN  # excluded: small island territory
- IND
# - IOT  # No level-1 GADM data
- IRL
- IRN
- IRQ
- ISL
- ISR
- ITA
- JAM
# - JEY  # No regions (microstate)
- JOR
- JPN
- KAZ
- KEN
- KGZ
- KHM
# - KIR  # No level-1 GADM data
# - KNA  # excluded: small island state
- KOR
# - KWT  # excluded: desert city-state
- LAO
- LBN
- LBR
- LBY
# - LCA  # excluded: small island state
# - LIE  # excluded: microstate
- LKA
- LSO
- LTU
- LUX
- LVA
# - MAC  # No level-1 GADM data
# - MAF  # No level-1 GADM data
- MAR
# - MCO  # No level-1 GADM data
- MDA
- MDG
# - MDV  # No level-1 GADM data
- MEX
# - MHL  # No regions (microstate)
- MKD
- MLI
- MLT
- MMR
- MNE
- MNG
# - MNP  # excluded: small island territory
- MOZ
- MRT
# - MSR  # excluded: small island territory
# - MTQ  # excluded: overseas department
- MUS
- MWI
- MYS
# - MYT  # excluded: overseas department
- NAM
# - NCL  # excluded: overseas territory
- NER
# - NFK  # No level-1 GADM data
- NGA
- NIC
# - NIU  # No level-1 GADM data
- NLD
- NOR
- NPL
# - NRU  # No regions (microstate)
- NZL
- OMN
- PAK
- PAN
# - PCN  # No level-1 GADM data
- PER
- PHL
# - PLW  # excluded: small island state
- PNG
- POL
- PRI
- PRK
- PRT
- PRY
- PSE
# - PYF  # excluded: overseas territory
# - QAT  # excluded: desert city-state
# - REU  # excluded: overseas department
- ROU
- RUS
- RWA
- SAU
- SDN
- SEN
# - SGP  # excluded: desert city-state (urban)
# - SGS  # No level-1 GADM data
# - SHN  # excluded: small island territory
# - SJM  # No population
- SLB
- SLE
- SLV
# - SMR  # No regions (microstate)
- SOM
# - SPM  # excluded: small island territory
- SRB
- SSD
- STP
- SUR
- SVK
- SVN
- SWE
- SWZ
# - SXM  # No level-1 GADM data
# - SYC  # excluded: small island state
- SYR
# - TCA  # excluded: small island territory
- TCD
- TGO
- THA
- TJK
# - TKL  # No regions (microstate)
- TKM
- TLS
# - TON  # excluded: small island state
- TTO
- TUN
- TUR
# - TUV  # No regions (microstate)
- TWN
- TZA
- UGA
- UKR
# - UMI  # No population
- URY
- USA
- UZB
# - VAT  # No level-1 GADM data
# - VCT  # excluded: small island state
- VEN
# - VGB  # excluded: small island territory
# - VIR  # excluded: small island territory
- VNM
- VUT
# - WLF  # excluded: overseas territory
# - WSM  # excluded: small island state
- YEM
- ZAF
- ZMB
- ZWE

data:
  gaez:
    climate_model: "NorESM1-M"
    time_period: "2020s" # "2020s", "2050s", "2080s"; these are 30 year averages from climate ensembles centered on the given decade.
    actual_yield_year: "2010" # "2000", "2010"; year for actual historical yeilds
    rcp: "4p5" # "2p6", "4p5", "6p0", "8p5"
    input_management: "H" # "H" (High), "L" (Low)
    water_supply: "r" # "r" (rainfed), "i" (irrigated)
    co2_fertilization: "" # "" (with) or "0" (without)
    yield_var: "yc" # "Average attainable yield, current cropland" (GAEZ documentation, page 129)
    suitability_var: "sx1" # "Share of gridcell assessed as VS or S" (i.e. very suitable or suitable; GAEZ documentation, page 129)
    crops:
      alfalfa: alf
      banana: ban
      buckwheat: bck
      barley: brl
      biomass-sorghum: bsg
      cabbage: cab
      carrot: car
      chickpea: chk
      citrus: cit
      cocoa: coc
      coffee: cof
      coconut: con
      cotton: cot
      cowpea: cow
      cassava: csv
      flax: flx
      foxtail-millet: fml
      groundnut: grd
      gram: grm
      jatropha: jtr
      miscanthus: mis
      maize: mze
      silage-maize: mzs
      napier-grass: nap
      oat: oat
      oil-palm: olp
      olive: olv
      onion: oni
      dry-pea: pea
      phaseolus bean: phb
      pigeonpea: pig
      pearl-millet: pml
      dryland-rice: rcd
      reed-canary grass: rcg
      wetland-rice: rcw
      rapeseed: rsd
      rubber: rub
      rye: rye
      sunflower: sfl
      soybean: soy
      sweet-potato: spo
      sorghum: srg
      sugarbeet: sub
      sugarcane: suc
      switchgrass: swg
      tea: tea
      tobacco: tob
      tomato: tom
      wheat: whe
      white-potato: wpo
      yam: yam
    actual_yield_crops:
    # GAEZ only has actual yields for the following crops
    - ban
    - brl
    - cot
    - grd
    - mze
    - olp
    - olv
    - rsd
    - srg
    - soy
    - sub
    - suc
    - sfl
    - tob
    - rcw
    - whe
    # GAEZ also has aggregate actual yields for millet, other cereals, potato & sweet potato and pulses. We ignore those here for simplicity
    # - fml pml
    # - oat rye
    # - wpo spo
    # - chk pea cow grm phb pig

irrigation:
  # Which model crops are allowed to have irrigated production.
  # Options:
  # - a list of crop names (as in 'crops' above)
  # - the string "auto" to detect availability by probing the GAEZ endpoints
  irrigated_crops: "auto"

solving:
  solver: highs
  # solver: gurobi
  options_gurobi:
    LogToConsole: 0
    OutputFlag: 1
    Method: 2
  options_highs:
    solver: "ipm"
