# SPDX-FileCopyrightText: 2025 Koen van Greevenbroek
#
# SPDX-License-Identifier: CC-BY-4.0

name: "toy"

primary:
  land:
    limit: 1e9 # ha
  water:
    limit: 1e9 # m^3
  fertilizer:
    limit: 1e9 # kg

crops:
- wheat
- dryland rice
- wetland rice
- maize
- soybean
- white potato
- tomato
- barley
- oat
- sunflower
- carrot
- onion
- cabbage
- banana

population: 7000000000 # Approx world population

macronutrients:
  carb:
    min_per_person_per_day: 300  # g/person/day (45-65% of calories, ~2000 cal/day)
  protein:
    min_per_person_per_day: 50   # g/person/day (10-35% of calories)
  fat:
    min_per_person_per_day: 65   # g/person/day (20-35% of calories)

food_groups:
  whole grain:
    min_per_person_per_day: 170  # g/person/day (WHO recommendations)
  grain:
    min_per_person_per_day: 150  # g/person/day (refined grains)
  fruit:
    min_per_person_per_day: 200  # g/person/day (WHO: 400g fruit+veg, split evenly)
  vegetable:
    min_per_person_per_day: 200  # g/person/day (WHO: 400g fruit+veg, split evenly)
  starchy vegetable:
    min_per_person_per_day: 100  # g/person/day (potatoes, etc.)
  oil:
    min_per_person_per_day: 25   # g/person/day (essential fats)

aggregation:
  regions: "countries"
  resource_class_quantiles: [0.25, 0.5, 0.75]

data:
  gaez:
    climate_model: "NorESM1-M"
    time_period: "2020s" # "2020s", "2050s", "2080s"; these are 30 year averages from climate ensembles centered on the given decade.
    rcp: "4p5" # "2p6", "4p5", "6p0", "8p5"
    input_management: "H" # "H" (High), "L" (Low)
    water_supply: "r" # "r" (rainfed), "i" (irrigated)
    co2_fertilization: "" # "" (with) or "0" (without)
    yield_var: "yc" # "Average attainable yield, current cropland" (GAEZ documentation, page 129)
    suitability_var: "sx1" # "Share of gridcell assessed as VS or S" (i.e. very suitable or suitable; GAEZ documentation, page 129)
    crops:
      alfalfa: alf
      banana: ban
      buckwheat: bck
      barley: brl
      biomass sorghum: bsg
      cabbage: cab
      carrot: car
      chickpea: chk
      citrus: cit
      cocoa: coc
      coffee: cof
      coconut: con
      cotton: cot
      cowpea: cow
      cassava: csv
      flax: flx
      foxtail millet: fml
      groundnut: grd
      gram: grm
      jatropha: jtr
      miscanthus: mis
      maize: mze
      silage maize: mzs
      napier grass: nap
      oat: oat
      oil palm: olp
      olive: olv
      onion: oni
      dry pea: pea
      phaseolus bean: phb
      pigeonpea: pig
      pearl millet: pml
      dryland rice: rcd
      reed canary grass: rcg
      wetland rice: rcw
      rapeseed: rsd
      rubber: rub
      rye: rye
      sunflower: sfl
      soybean: soy
      sweet potato: spo
      sorghum: srg
      sugarbeet: sub
      sugarcane: suc
      switchgrass: swg
      tea: tea
      tobacco: tob
      tomato: tom
      wheat: whe
      white potato: wpo
      yam: yam

solving:
  solver: gurobi
  solver_options:
    LogToConsole: 1
    OutputFlag: 1
