# SPDX-FileCopyrightText: 2025 Koen van Greevenbroek
#
# SPDX-License-Identifier: CC-BY-4.0

name: food-opt
channels:
- conda-forge
- bioconda
dependencies:
- python>=3.12
- pip
- snakemake>=9.0

- pypsa>=0.35

- seaborn
- numpy
- pandas>=2.1
- matplotlib

- jupyter
- ipython
- pre-commit
- ruff

- pip:
  - gurobipy
  - highspy
