# SPDX-FileCopyrightText: 2025 Koen van Greevenbroek
#
# SPDX-License-Identifier: CC-BY-4.0

name: docs

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-docs:
    name: Build documentation
    runs-on: ubuntu-latest
    env:
      UV_CACHE_DIR: .uv-cache

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install uv
        uses: astral-sh/setup-uv@v1

      - name: Cache uv artifacts
        uses: actions/cache@v4
        with:
          path: .uv-cache
          key: ${{ runner.os }}-uv-${{ hashFiles('uv.lock') }}

      - name: Sync dependencies
        run: uv sync --extra dev

      - name: Build HTML docs
        run: uv run python -m sphinx -b html docs docs/_build/html

      - name: Upload docs artifact
        uses: actions/upload-artifact@v4
        with:
          name: docs-html
          path: docs/_build/html
          if-no-files-found: error
